# apiVersion: networking.k8s.io/v1
# kind: NetworkPolicy
# metadata:
#   name: backend-policy
#   namespace: backend
# spec:
#   podSelector: {}
#   ingress:
#     - from:
#         - namespaceSelector:
#             matchLabels:
#               name: frontend
#       ports:
#         - protocol: TCP
#           port: 3000
#   policyTypes:
#     - Ingress
