# apiVersion: networking.k8s.io/v1
# kind: NetworkPolicy
# metadata:
#   name: frontend-policy
#   namespace: frontend
# spec:
#   podSelector: {}
#   ingress:
#     - from:
#         - namespaceSelector:
#             matchLabels:
#               name: backend
#       ports:
#         - protocol: TCP
#           port: 80
#   policyTypes:
#     - Ingress
