# apiVersion: networking.k8s.io/v1
# kind: NetworkPolicy
# metadata:
#   name: mongo-policy
#   namespace: database
# spec:
#   podSelector: {}
#   ingress:
#     - from:
#         - namespaceSelector:
#             matchLabels:
#               name: backend
#       ports:
#         - protocol: TCP
#           port: 27017
#   policyTypes:
#     - Ingress