apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: backend-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: backend  # Deployment name to apply HPA
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 50  # CPU usage threshold
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 60
      selectPolicy: Max
      policies:
        - type: Percent
          value: 200  # Scale up by up to 200%
          periodSeconds: 30  # Set periodSeconds to a valid value (e.g., 30)
    scaleDown:
      stabilizationWindowSeconds: 60
      selectPolicy: Min
      policies:
        - type: Percent
          value: 50  # Scale down by at least 50%
          periodSeconds: 30  # Set periodSeconds to a valid value (e.g., 30)
