apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: 619715105204.dkr.ecr.us-east-1.amazonaws.com/docktor-app/doctor-office-backend:stateful
        resources:
          requests:
            cpu: "100m"   # min CPU requests
            memory: "256Mi"  # min memory requests
          limits:
            cpu: "200m"   # max CPU requests
            memory: "512Mi"  # max memory requests
        ports:
        - containerPort: 3000
        env:
        - name: MONGODB_URL
          value: "mongo-0.mongo.default.svc.cluster.local,mongo-1.mongo.default.svc.cluster.local,mongo-2.mongo.default.svc.cluster.local:27017" #"mongo-service.default.svc.cluster.local:27017"  
#      imagePullSecrets:
#      - name: myregistry-secret

---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  # type: LoadBalancer
