apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      imagePullSecrets:
      - name: ecr-secret
      containers:
      - name: frontend
        image: 913524912273.dkr.ecr.us-east-1.amazonaws.com/docktor-app/doctor-office-frontend:latest
        resources:  # Set resource requests and limits for stable performance and HPA support.
          requests:
            cpu: "100m"   # min CPU requests
            memory: "256Mi"  # min memory requests
          limits:
            cpu: "200m"   # max CPU requests
            memory: "512Mi"  # max memory requests
        ports:
        - containerPort: 3001
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: default.conf
      volumes:
      - name: nginx-config
        configMap:
          name: frontend-nginx-config
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: frontend
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3001
  # type: LoadBalancer
  type: NodePort
