apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
  namespace: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
      - name: mongo
        image: mongo
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: root   # MongoDB root username
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongo-secret         # Reference to the secret containing the MongoDB root password
              key: mongo_root_password   # Key within the secret to retrieve the password
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-service
  namespace: database
spec:
  selector:
    app: mongo
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
